import Foundation

/// Represents a personalized activity recommendation generated by the AI
/// This is the "payoff" - the hyper-specific event suggestion based on the conversation
struct GeneratedActivity: Codable {
    /// Eye-catching title like "Sunset Wine & Wisdom for Career Changers"
    let title: String

    /// 2-3 sentence description of what the activity involves
    let description: String

    /// Who's invited - the niche criteria e.g., "5 women in the Marina going through breakups"
    let targetAudience: String

    /// Real SF Bay Area location where the event would happen
    let location: String

    /// When the event would occur (within next 2 weeks)
    let datetime: String

    /// The mood/tone of the event e.g., "intimate", "reflective", "energizing"
    let vibe: String
}

// MARK: - Sample Data for Previews
extension GeneratedActivity {
    static let sample = GeneratedActivity(
        title: "Sunset Dinner for Women Navigating Career Pivots",
        description: "An intimate dinner at a cozy Marina restaurant where 5 women share their career transition stories over wine and locally-sourced food. Expect honest conversations about fear, excitement, and reinvention.",
        targetAudience: "5 women in their 30s navigating major career changes",
        location: "The Interval at Long Now, Fort Mason",
        datetime: "Saturday, February 15th at 6:30 PM",
        vibe: "Warm, supportive, and inspiring"
    )
}
