import SwiftUI

struct SummaryView: View {
    @EnvironmentObject var state: AppState
    let newMessageCount: Int

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 12) {
                contactHeader
                if isPaused {
                    pausedBanner
                }
                if newMessageCount > 0 {
                    Label(
                        "\(newMessageCount) new message\(newMessageCount == 1 ? "" : "s") included",
                        systemImage: "sparkles"
                    )
                    .font(.caption)
                    .foregroundStyle(.secondary)
                }

                if let summary = state.currentSummary {
                    bullets(summary.bulletPoints)
                    if !summary.summaryText.isEmpty {
                        Divider()
                        Text(summary.summaryText)
                            .font(.callout)
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                    metadata(summary)
                } else {
                    Text("No summary yet.")
                        .foregroundStyle(.secondary)
                        .font(.callout)
                }

                Spacer(minLength: 0)
            }
            .padding(12)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }

    private var isPaused: Bool {
        state.activeContact?.isBlacklisted ?? false
    }

    private var pausedBanner: some View {
        HStack(spacing: 6) {
            Image(systemName: "pause.circle.fill")
            Text("Paused — not generating new summaries")
                .font(.caption)
            Spacer()
        }
        .foregroundStyle(.orange)
        .padding(8)
        .background(
            RoundedRectangle(cornerRadius: 6)
                .fill(Color.orange.opacity(0.12))
        )
    }

    private var contactHeader: some View {
        let displayName = state.activeContact?.bestDisplayName
            ?? state.activeContactDisplay
            ?? "Unknown"
        let phone = state.activeContact?.phoneOrEmail ?? state.activeHandleID ?? ""

        return VStack(alignment: .leading, spacing: 2) {
            Text(displayName).font(.headline)
            if !phone.isEmpty {
                Text(phone)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }

    private func bullets(_ points: [String]) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(Array(points.enumerated()), id: \.offset) { _, point in
                HStack(alignment: .top, spacing: 8) {
                    Text("•")
                        .font(.body)
                        .foregroundStyle(.secondary)
                    Text(point)
                        .font(.body)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
    }

    private func metadata(_ summary: Summary) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack {
                Text("Updated \(Self.relative.localizedString(for: summary.createdAt, relativeTo: Date()))")
                Spacer()
                Button(isPaused ? "Unpause" : "Pause") {
                    Task { await SummaryActions.setBlacklisted(state, isBlacklisted: !isPaused) }
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
                Button("Regenerate") {
                    Task { await SummaryActions.regenerate(state) }
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
                .disabled(isPaused)
            }
            Text("Generated by \(summary.generatedBy) · \(summary.modelVersion)")
                .foregroundStyle(.tertiary)
        }
        .font(.caption)
        .foregroundStyle(.secondary)
        .padding(.top, 4)
    }

    private static let relative: RelativeDateTimeFormatter = {
        let f = RelativeDateTimeFormatter()
        f.unitsStyle = .abbreviated
        return f
    }()
}

enum SummaryActions {
    @MainActor
    static func setBlacklisted(_ state: AppState, isBlacklisted: Bool) async {
        guard let contact = state.activeContact, let repo = state.contactsRepo else { return }
        do {
            let updated = try await repo.setBlacklisted(contactID: contact.id, isBlacklisted: isBlacklisted)
            state.activeContact = updated
            if let idx = state.allSummarizedContacts.firstIndex(where: { $0.id == updated.id }) {
                state.allSummarizedContacts[idx] = updated
            }
            // Unpausing should re-run the pipeline (NOT a force regenerate)
            // so a still-fresh cached summary stays cached.
            if !isBlacklisted, state.activeHandleID != nil {
                NotificationCenter.default.post(name: .iMessageSummaryRefresh, object: nil)
            }
        } catch {
            state.viewState = .error("Couldn't update pause state: \(error)")
        }
    }

    @MainActor
    static func regenerate(_ state: AppState) async {
        if let handle = state.activeHandleID {
            NotificationCenter.default.post(name: .iMessageSummaryRegenerate, object: handle)
        }
    }
}

extension Notification.Name {
    static let iMessageSummaryRegenerate = Notification.Name("iMessageSummary.regenerate")
    static let iMessageSummarySelectContact = Notification.Name("iMessageSummary.selectContact")
    static let iMessageSummaryRefresh = Notification.Name("iMessageSummary.refresh")
}
