import SwiftUI

struct SummaryView: View {
    @EnvironmentObject var state: AppState
    let newMessageCount: Int

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 12) {
                contactHeader

                if newMessageCount > 0 {
                    Label(
                        "\(newMessageCount) new message\(newMessageCount == 1 ? "" : "s") included",
                        systemImage: "sparkles"
                    )
                    .font(.caption)
                    .foregroundStyle(.secondary)
                }

                if let summary = state.currentSummary {
                    bullets(summary.bulletPoints)
                    if !summary.summaryText.isEmpty {
                        Divider()
                        Text(summary.summaryText)
                            .font(.callout)
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                    metadata(summary)
                } else {
                    Text("No summary yet.")
                        .foregroundStyle(.secondary)
                        .font(.callout)
                }

                Spacer(minLength: 0)
            }
            .padding(12)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }

    private var contactHeader: some View {
        let displayName = state.activeContact?.bestDisplayName
            ?? state.activeContactDisplay
            ?? "Unknown"
        let phone = state.activeContact?.phoneOrEmail ?? state.activeHandleID ?? ""
        let isBlacklisted = state.activeContact?.isBlacklisted ?? false

        return VStack(alignment: .leading, spacing: 2) {
            HStack {
                Text(displayName).font(.headline)
                Spacer()
                Toggle(isOn: Binding(
                    get: { isBlacklisted },
                    set: { newValue in
                        Task { await SummaryActions.setBlacklisted(state, isBlacklisted: newValue) }
                    }
                )) { Text("") }
                    .toggleStyle(.switch)
                    .labelsHidden()
                    .help("Pause summaries for this contact")
            }
            if !phone.isEmpty {
                Text(phone)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }

    private func bullets(_ points: [String]) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            ForEach(Array(points.enumerated()), id: \.offset) { _, point in
                HStack(alignment: .top, spacing: 8) {
                    Text("•")
                        .font(.body)
                        .foregroundStyle(.secondary)
                    Text(point)
                        .font(.body)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
    }

    private func metadata(_ summary: Summary) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            HStack {
                Text("Updated \(Self.relative.localizedString(for: summary.createdAt, relativeTo: Date()))")
                Spacer()
                Button("Regenerate") {
                    Task { await SummaryActions.regenerate(state) }
                }
                .buttonStyle(.bordered)
                .controlSize(.small)
            }
            Text("Generated by \(summary.generatedBy) · \(summary.modelVersion)")
                .foregroundStyle(.tertiary)
        }
        .font(.caption)
        .foregroundStyle(.secondary)
        .padding(.top, 4)
    }

    private static let relative: RelativeDateTimeFormatter = {
        let f = RelativeDateTimeFormatter()
        f.unitsStyle = .abbreviated
        return f
    }()
}

/// Action stubs for buttons inside SummaryView. Real implementations live on
/// the pipeline (step 9 / 12); this layer just dispatches to it via AppState.
enum SummaryActions {
    @MainActor
    static func setBlacklisted(_ state: AppState, isBlacklisted: Bool) async {
        guard let contact = state.activeContact, let repo = state.contactsRepo else { return }
        do {
            let updated = try await repo.setBlacklisted(contactID: contact.id, isBlacklisted: isBlacklisted)
            state.activeContact = updated
            if let idx = state.allSummarizedContacts.firstIndex(where: { $0.id == updated.id }) {
                state.allSummarizedContacts[idx] = updated
            }
            state.viewState = isBlacklisted ? .blacklisted : .loaded(newMessageCount: 0)
        } catch {
            state.viewState = .error("Couldn't update blacklist: \(error)")
        }
    }

    @MainActor
    static func regenerate(_ state: AppState) async {
        // Real flow lives in SidebarPipeline (step 9). This is a placeholder so
        // the button is non-fatal during step 5–7.
        if let handle = state.activeHandleID {
            NotificationCenter.default.post(name: .iMessageSummaryRegenerate, object: handle)
        }
    }
}

extension Notification.Name {
    static let iMessageSummaryRegenerate = Notification.Name("iMessageSummary.regenerate")
    static let iMessageSummarySelectContact = Notification.Name("iMessageSummary.selectContact")
}
